# Generated by Django 2.0.1 on 2018-01-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JokeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashId', models.CharField(max_length=35)),
                ('content', models.TextField()),
                ('unixtime', models.IntegerField()),
                ('updatetime', models.DateTimeField()),
                ('url', models.ImageField(upload_to='')),
            ],
        ),
    ]
